# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cadi?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath*
